package ch.devprojects.orderflow.mapper;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigDecimal;
import java.time.Instant;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import ch.devprojects.orderflow.domain.Order;
import ch.devprojects.orderflow.domain.OrderStatus;
import ch.devprojects.orderflow.dto.OrderDto;

/**
 * Pure unit tests for {@link OrderMapper}.
 *
 * This test:
 *  - increases line/branch coverage for the mapper.
 *  - protects the mapping contract between Order (entity) and OrderDto (API).
 *
 * We do NOT start Spring here – this is a simple, fast, isolated test.
 */
class OrderMapperTest {

    private final OrderMapper mapper = new OrderMapper();

    // -------------------------------------------------------------------------
    // toDto(...)
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("toDto(null) should return null")
    void toDto_shouldReturnNull_whenEntityIsNull() {
        // Act
        OrderDto dto = mapper.toDto(null);

        // Assert
        assertNull(dto, "Mapping a null entity should return null DTO");
    }

    @Test
    @DisplayName("toDto should map all simple fields from entity to DTO")
    void toDto_shouldMapAllFields() {
        // Arrange: build an entity with all fields filled
        Order entity = new Order();
        entity.setId(10L);
        entity.setCode("ORD-10");
        entity.setStatus(OrderStatus.PROCESSING);
        entity.setTotal(BigDecimal.valueOf(99.99));

        Instant created = Instant.parse("2025-01-01T10:00:00Z");
        Instant updated = Instant.parse("2025-01-02T11:00:00Z");
        entity.setCreatedAt(created);
        entity.setUpdatedAt(updated);

        // Act
        OrderDto dto = mapper.toDto(entity);

        // Assert: all relevant fields should be copied 1:1
        assertNotNull(dto, "DTO must not be null");
        assertEquals(10L, dto.getId());
        assertEquals("ORD-10", dto.getCode());
        assertEquals(OrderStatus.PROCESSING, dto.getStatus());
        assertEquals(BigDecimal.valueOf(99.99), dto.getTotal());
        assertEquals(created, dto.getCreatedAt());
        assertEquals(updated, dto.getUpdatedAt());
        // customerName is DTO-only and intentionally NOT set by mapper
        assertNull(dto.getCustomerName(), "customerName is DTO-only and should remain null");
    }

    // -------------------------------------------------------------------------
    // toEntity(...)
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("toEntity(null) should return null")
    void toEntity_shouldReturnNull_whenDtoIsNull() {
        // Act
        Order entity = mapper.toEntity(null);

        // Assert
        assertNull(entity, "Mapping a null DTO should return null entity");
    }

    @Test
    @DisplayName("toEntity should map all simple fields from DTO to entity")
    void toEntity_shouldMapAllFields() {
        // Arrange: build a DTO with all relevant fields
        OrderDto dto = new OrderDto();
        dto.setId(99L); // NOTE: mapper does NOT copy id from DTO to entity (by design)
        dto.setCode("ORD-99");
        dto.setStatus(OrderStatus.PAID);
        dto.setTotal(BigDecimal.valueOf(123.45));

        Instant created = Instant.parse("2025-02-01T12:00:00Z");
        Instant updated = Instant.parse("2025-02-02T13:00:00Z");
        dto.setCreatedAt(created);
        dto.setUpdatedAt(updated);

        // Act
        Order entity = mapper.toEntity(dto);

        // Assert
        assertNotNull(entity, "Entity must not be null");
        // ID is generated by JPA and not set from DTO in current mapper
        assertNull(entity.getId(), "ID is not mapped from DTO to entity (JPA will generate it)");
        assertEquals("ORD-99", entity.getCode());
        assertEquals(OrderStatus.PAID, entity.getStatus());
        assertEquals(BigDecimal.valueOf(123.45), entity.getTotal());
        assertEquals(created, entity.getCreatedAt());
        assertEquals(updated, entity.getUpdatedAt());
    }

    // -------------------------------------------------------------------------
    // updateEntityFromDto(...)
    // -------------------------------------------------------------------------

    @Test
    @DisplayName("updateEntityFromDto should do nothing when DTO is null")
    void updateEntityFromDto_shouldDoNothing_whenDtoIsNull() {
        // Arrange
        Order entity = new Order();
        entity.setCode("ORD-BASE");
        entity.setStatus(OrderStatus.NEW);
        entity.setTotal(BigDecimal.TEN);
        Instant originalUpdatedAt = entity.getUpdatedAt(); // created by default in entity ctor

        // Act
        mapper.updateEntityFromDto(null, entity);

        // Assert: entity unchanged
        assertEquals("ORD-BASE", entity.getCode());
        assertEquals(OrderStatus.NEW, entity.getStatus());
        assertEquals(BigDecimal.TEN, entity.getTotal());
        assertEquals(originalUpdatedAt, entity.getUpdatedAt(),
                "updatedAt must not change when DTO is null");
    }

    @Test
    @DisplayName("updateEntityFromDto should do nothing when entity is null")
    void updateEntityFromDto_shouldDoNothing_whenEntityIsNull() {
        // Act + Assert: must not throw
        assertDoesNotThrow(
                () -> mapper.updateEntityFromDto(new OrderDto(), null),
                "updateEntityFromDto(dto, null) must not throw"
        );
    }

    @Test
    @DisplayName("updateEntityFromDto should update changed fields and touch updatedAt")
    void updateEntityFromDto_shouldUpdateFieldsAndUpdatedAt_whenValuesDiffer() {
        // Arrange: entity with base values
        Order entity = new Order();
        entity.setCode("ORD-OLD");
        entity.setStatus(OrderStatus.NEW);
        entity.setTotal(BigDecimal.valueOf(10.00));

        Instant createdAt = Instant.parse("2025-03-01T10:00:00Z");
        Instant originalUpdatedAt = Instant.parse("2025-03-01T11:00:00Z");
        entity.setCreatedAt(createdAt);
        entity.setUpdatedAt(originalUpdatedAt);

        // DTO with new values for some fields
        OrderDto dto = new OrderDto();
        dto.setCode("ORD-NEW");                       // changed
        dto.setStatus(OrderStatus.SHIPPED);           // changed
        dto.setTotal(BigDecimal.valueOf(20.00));      // changed
        // createdAt in DTO is null -> mapper must NOT overwrite entity.createdAt

        // Act
        mapper.updateEntityFromDto(dto, entity);

        // Assert: changed fields updated
        assertEquals("ORD-NEW", entity.getCode());
        assertEquals(OrderStatus.SHIPPED, entity.getStatus());
        assertEquals(BigDecimal.valueOf(20.00), entity.getTotal());
        // createdAt must stay the original value
        assertEquals(createdAt, entity.getCreatedAt(), "createdAt must not be modified");

        // And updatedAt must be refreshed because something changed
        Instant newUpdatedAt = entity.getUpdatedAt();
        assertNotNull(newUpdatedAt, "updatedAt must not be null after update");
        assertNotEquals(originalUpdatedAt, newUpdatedAt,
                "updatedAt must be changed when at least one field changed");
    }

    @Test
    @DisplayName("updateEntityFromDto should NOT change updatedAt when no field changes")
    void updateEntityFromDto_shouldNotChangeUpdatedAt_whenNothingChanged() {
        // Arrange: entity with specific values
        Order entity = new Order();
        entity.setCode("ORD-SAME");
        entity.setStatus(OrderStatus.PROCESSING);
        entity.setTotal(BigDecimal.valueOf(50.00));

        Instant createdAt = Instant.parse("2025-04-01T08:00:00Z");
        Instant originalUpdatedAt = Instant.parse("2025-04-01T09:00:00Z");
        entity.setCreatedAt(createdAt);
        entity.setUpdatedAt(originalUpdatedAt);

        // DTO with exactly the same values (no real change)
        OrderDto dto = new OrderDto();
        dto.setCode("ORD-SAME");
        dto.setStatus(OrderStatus.PROCESSING);
        dto.setTotal(BigDecimal.valueOf(50.00));
        dto.setCreatedAt(createdAt);  // same as entity
        dto.setUpdatedAt(originalUpdatedAt); // this field is ignored by mapper for updatedAt

        // Act
        mapper.updateEntityFromDto(dto, entity);

        // Assert: nothing should have changed
        assertEquals("ORD-SAME", entity.getCode());
        assertEquals(OrderStatus.PROCESSING, entity.getStatus());
        assertEquals(BigDecimal.valueOf(50.00), entity.getTotal());
        assertEquals(createdAt, entity.getCreatedAt());
        assertEquals(originalUpdatedAt, entity.getUpdatedAt(),
                "updatedAt must stay the same when no effective field changed");
    }
}