-- Schema version: 1
-- Purpose: create initial table for Order aggregate

create table if not exists orders (
  id          bigint generated by default as identity primary key,
  code        varchar(64)   not null unique,
  total       decimal(14,2) not null,
  status      varchar(16)   not null,
  created_at  timestamp,
  updated_at  timestamp
);